build:
	gcc -std=c++17 commands.h game_state.h gui_state.h cl_state.h game_state.cpp gui_state.cpp cl_state.cpp main.cpp -o main -lsfml-graphics -lsfml-window -lsfml-system -lstdc++
run:
	./main
clean: 
	rm -fr main